server:
  servlet:
    context-path: /api/v1
  port: 8080

spring:
  web:
    locale: pt_BR
    locale-resolver: fixed
  application:
    name: gym
  profiles:
    active: ${AMBIENTE}
  datasource:
    url: jdbc:postgresql://${GYM_DB_HOST}/${GYM_DB_NAME}
    username: ${GYM_DB_USER}
    password: ${GYM_DB_PASSWORD}
    driver-class-name: ${GYM_DB_DRIVER}